@echo off
echo ============================================
echo Fixing validation issues and redeploying
echo ============================================

cd /d "%~dp0data_cleaning_env_project\data_cleaning_env"

echo.
echo Step 1: Installing uv and generating uv.lock...
pip install uv >nul 2>&1
uv lock 2>nul
if not exist uv.lock (
    echo uv lock failed, creating minimal lock file...
    echo # This file is generated by uv. > uv.lock
    echo version = 1 >> uv.lock
    echo requires-python = ">=3.10" >> uv.lock
)
echo uv.lock created!

echo.
echo Step 2: Deploying to GitHub...
cd /d "%~dp0"
python push_to_github.py

echo.
echo Step 3: Deploying to HuggingFace...
python deploy_to_hf.py

echo.
echo ============================================
echo All done! Wait 2-3 min for HF rebuild,
echo then click "Update Submission"
echo ============================================
pause
